### ISSUE TITLE
Issue with glib-compile-schema

### ISSUE THREAD

**Issue by fyberoptik** [PierreGoude/Linux-Active-Directory-join-script#2]
Firstly thanks for putting this script together, its very useful.

Unfortunately after using this script, I did run into a little problem when running glib-compile-schema against the usual directory /usr/share/glib-2.0/schemas. 

When you run the glib-compile-command it appears to run with no problem, however when you restart the machine the system complains that it doesn't know talk with the graphics card. I have gone over this a few times, I ran the glib compile right before running the join script. But I only get problems after the AD join has ran.

I don't know if you had any idea what could be causing this issue? Anything that might be affecting the /usr/share/glib-schema directory?

I'm running ubuntu 16.04 (unity)

**Comment by fyberoptik** [comment]
I have ran the same steps in a virtual machine and it didn't fail, will update.

**Comment by PierreGoude** [comment]
Aj ok, thanks. I Will test also. I should not affect it at all. Does nothing under that directory

**Comment by PierreGoude** [comment]
Hi! i did run sudo glib-compile-schemas /usr/share/glib-2.0/schemas/ without issues.

**Comment by fyberoptik** [comment]
This seems to be hardware specific on the iMac I'm using.

Feel free to close this case, it highly likely nothing to do with the AD script.

Thanks
